name: update figma

on:
    repository_dispatch:
        types: [update-tokens]
        
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo hi

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo ${{client_payload.tokens}}

        
