on:
    repository_dispatch:
        types: [update-tokens]

jobs:
  build:
   runs-on: ubuntu-latest
   steps:
   - name: Update theme file
     uses: DamianReeves/write-file-action@v1.0
     with:
       path: ./theme.json
       contents: ${{github.event.client_payload.tokens}}
       write-mode: overwrite
    
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - name: dispatch trigger
#       run: |
#         echo "repository_dispatch triggered"
#         echo ${{github.event.client_payload.tokens}}
