name: update figma

on:
    repository_dispatch:
        types: [update-tokens]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: dispatch trigger
      run: |
        echo "repository_dispatch triggered"
